// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmcQEAnwvUqHht4D3u9xPNvmfpHpoEgpU',
    appId: '1:379220315367:web:939cde6269e510da35a642',
    messagingSenderId: '379220315367',
    projectId: 'barebnb-c35a0',
    authDomain: 'barebnb-c35a0.firebaseapp.com',
    storageBucket: 'barebnb-c35a0.firebasestorage.app',
    measurementId: 'G-05LN5XM4T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCut88DLlW5sRlPoA8gQuqdjPp0DUPqYtw',
    appId: '1:379220315367:android:6d128c695768fa9335a642',
    messagingSenderId: '379220315367',
    projectId: 'barebnb-c35a0',
    storageBucket: 'barebnb-c35a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrzzk_UJJUUaQdX2Vt30_tk_TosZqolFk',
    appId: '1:379220315367:ios:1f03e3ccf28f049135a642',
    messagingSenderId: '379220315367',
    projectId: 'barebnb-c35a0',
    storageBucket: 'barebnb-c35a0.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrzzk_UJJUUaQdX2Vt30_tk_TosZqolFk',
    appId: '1:379220315367:ios:1f03e3ccf28f049135a642',
    messagingSenderId: '379220315367',
    projectId: 'barebnb-c35a0',
    storageBucket: 'barebnb-c35a0.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmcQEAnwvUqHht4D3u9xPNvmfpHpoEgpU',
    appId: '1:379220315367:web:ddfb10973809055935a642',
    messagingSenderId: '379220315367',
    projectId: 'barebnb-c35a0',
    authDomain: 'barebnb-c35a0.firebaseapp.com',
    storageBucket: 'barebnb-c35a0.firebasestorage.app',
    measurementId: 'G-014LDVS8E2',
  );
}
